name: GH build test

on:
  workflow_dispatch:
    inputs:
      sth:
        type: string
        required: false
        default: "noene"
  push:
    branches:
      - '*'

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        id: gh-script
        with:
          result-encoding: string
          script: | 
            a = github.rest.repos.listForOrg({
              org: "maikelos-test"
            });

            console.log(a)