name: GH build test

on:
  workflow_dispatch:
    inputs:
      sth:
        type: string
        required: false
        default: "noene"
  push:
    branches:
      - '*'

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        id: gh-script
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          result-encoding: string
          script: | 
            const repos = await github.rest.repos.listForOrg({
              org: "maikelos-test"
            });

            console.log(repos)

            const repo = await github.rest.repos.createInOrg({
              org: "maikelos-test",
              name: "auto-repo-test-4",
            });

            console.log(repo)
            
            const myvar = await github.rest.actions.createRepoVariable({
              owner: "maikelos-test",
              repo: "auto-repo-test-4",
              name: "TestVar",
              value: "TestVarValue",
            });

            console.log(myvar)